### ISSUE TITLE
README doxygen documentation link is broken

### ISSUE THREAD

**Issue by pratikpc** [morganstanley/modern-cpp-kafka#14]
Here is the doxygen documentation for developers.

Links to https://github.com/morganstanley/modern-cpp-kafka/blob/master/doxygen/annotated.html

404s currently

**Comment by kenneth-jia** [comment]
Thank you for pointing it out.
Currently, the doc link is only available after building the project. E.g. https://github.com/morganstanley/modern-cpp-kafka/blob/master/.github/workflows/gen_doc.yml#L33
I know there's a "Page" feature in GitHub, which could help fix the problem here. Let me find some time to learn the feature and fix the "404" in future.

**Comment by pratikpc** [comment]
@kenneth-jia yeah my idea would be
1. Using Github Pages to create a GitHub Pages website at morganstanley.github.io/modern-cpp-kafka
2. This could be handled via the Workflows as you showcase
3. I have a project called [Bunkstur-UI where I am using React and GitHub Pages to generate the site](https://github.com/pratikpc/Bunkstur-UI/blob/develop/.github/workflows/publish.yaml)
4. Something that might work here would be
```yaml
      - name: Config
        run: |
          cd $BUILD_SUB_DIR
          cmake ../.. -DBUILD_OPTION_DOC_ONLY=ON
      - name: Build
        run: |
          cd $BUILD_SUB_DIR
          make VERBOSE=1
      - name: Copy
        run: |
          mkdir doc-gen
          cp $BUILD_SUB_DIR/doc/README.html doc-gen
          cp -r $BUILD_SUB_DIR/doc/markdown doc-gen
          cp -r $BUILD_SUB_DIR/doc/doxygen doc-gen
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc-gen
```
4. By default, this deploys to gh-pages branch.
5. So you would have to enable it for that branch via [Repository Settings](https://github.com/morganstanley/modern-cpp-kafka/settings)
![image](https://user-images.githubusercontent.com/28534575/108658954-9d011900-74f0-11eb-9ce8-da1d8c109d40.png)
